# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import omlet_common.protos.container_pb2 as container__pb2


class ContainerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AttachStandardOutput = channel.unary_stream(
                '/omlet.ContainerService/AttachStandardOutput',
                request_serializer=container__pb2.AttachStandardOutputRequest.SerializeToString,
                response_deserializer=container__pb2.AttachStandardOutputResponse.FromString,
                )


class ContainerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AttachStandardOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AttachStandardOutput': grpc.unary_stream_rpc_method_handler(
                    servicer.AttachStandardOutput,
                    request_deserializer=container__pb2.AttachStandardOutputRequest.FromString,
                    response_serializer=container__pb2.AttachStandardOutputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omlet.ContainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContainerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AttachStandardOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/omlet.ContainerService/AttachStandardOutput',
            container__pb2.AttachStandardOutputRequest.SerializeToString,
            container__pb2.AttachStandardOutputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
